runtime: python27
api_version: 1
threadsafe: yes

handlers:

# The following are static *file* handlers.
# You need to specify which files to upload
# because url can contain regexes and thus
# handler cannot determine which files to
# upload.
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
  redirect_http_response_code: 301

- url: /
  static_files: index.html
  upload: index\.html
  secure: always
  redirect_http_response_code: 301

# All other URLs use the main.py script.
# This app is using WSGI instead of CGI.
- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
