service: redirect
runtime: go114

handlers:
# The only accepted value for the script element is auto because all
# traffic is served using the entrypoint command.
- url: /.*
  script: auto

automatic_scaling:
  max_instances: 1
